version: "3"
services:
  nginx:
    image: nginx:1.15-alpine
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/public:/var/www/html
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "2"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  mongo:
    image: mongo:3.6.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    # ports:
    #   - "27017:27017"
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"
    volumes:
      - ./data/mongo:/data/db
  keystone:
    build: ./keystone
    restart: always
    environment:
      - KEYSTONE_ADMIN_EMAIL=${KEYSTONE_ADMIN_EMAIL}
      - KEYSTONE_ADMIN_PASSWORD=${KEYSTONE_ADMIN_PASSWORD}
      - KEYSTONE_COOKIE_SECRET=${KEYSTONE_COOKIE_SECRET}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"
