version: "3"
services:
  nginx:
    image: nginx:1.15-alpine
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./blog/build:/var/www/html
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "2"
  mongo:
    image: mongo:3.6.2
    env_file:
      - .mongo_env
    # ports:
    #   - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"
  strapi:
    build: .
    image: strapi/strapi
    env_file:
      - .strapi_env
    # ports:
    #   - 1337:1337
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
    depends_on:
      - mongo
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"
